In [1]:
import torch

In [2]:
import torch.nn as nn

In [3]:
fc = nn.Linear(3, 2)

In [4]:
fc

Linear(in_features=3, out_features=2, bias=True)

In [5]:
fc.weight

Parameter containing:
tensor([[ 0.2247,  0.2381, -0.1099],
        [ 0.0791, -0.4521, -0.2842]], requires_grad=True)

In [6]:
fc.bias

Parameter containing:
tensor([-0.0554, -0.3951], requires_grad=True)

In [7]:
torch.manual_seed(0)

In [9]:
fc = nn.Linear(3, 2)

In [10]:
fc.weight

Parameter containing:
tensor([[-0.0043,  0.3097, -0.4752],
        [-0.4249, -0.2224,  0.1548]], requires_grad=True)

In [11]:
fc.bias

Parameter containing:
tensor([-0.0114,  0.4578], requires_grad=True)

In [12]:
x = torch.tensor([[1.,2.,3.]])

In [14]:
type(x), x.dtype

(torch.Tensor, torch.float32)

In [15]:
u = fc(x)

In [16]:
u

tensor([[-0.8219,  0.0526]], grad_fn=<AddmmBackward0>)

In [17]:
import torch.nn.functional as F

In [18]:
h = F.relu(u)

In [20]:
h

tensor([[0.0000, 0.0526]], grad_fn=<ReluBackward0>)

In [21]:
t = torch.tensor([[1.],[3.]])

In [22]:
y = torch.tensor([[2.],[4.]])

In [23]:
F.mse_loss(y, t)

tensor(1.)

In [24]:
from sklearn.datasets import load_iris

In [25]:
iris = load_iris()

In [31]:
x = iris['data']
t = iris['target']

In [32]:
x = torch.tensor(x, dtype=torch.float32)
t = torch.tensor(t, dtype=torch.int64)

In [33]:
type(x), type(t)

(torch.Tensor, torch.Tensor)

In [34]:
x.shape, t.shape

(torch.Size([150, 4]), torch.Size([150]))

In [36]:
dataset = torch.utils.data.TensorDataset(x, t)

In [38]:
dataset[0]

(tensor([5.1000, 3.5000, 1.4000, 0.2000]), tensor(0))

In [39]:
n_train = int(len(dataset) * 0.6)
n_val = int(len(dataset) * 0.2)
n_test = len(dataset) - n_train - n_val

In [40]:
n_train, n_val, n_test

(90, 30, 30)

In [41]:
torch.manual_seed(0)

In [42]:
train, val, test = torch.utils.data.random_split(dataset, [n_train, n_val, n_test])

In [43]:
len(train), len(val), len(test)

(90, 30, 30)